spring:
    application:
        name: binance
    profiles:
        active: local

binance:
    domain:
        main: "https://fapi.binance.com"
        get:
            time: "/fapi/v1/time"
        klines: "/fapi/v1/klines"
        ws: "wss://fstream.binance.com/stream"
telegram:
    domain: https://api.telegram.org/bot${telegram.token}/sendMessage

coin:
    symbol: "ETHUSDT"